package lowLevelDesignModuleTwo.QuestionAnswer.BackendLLDDesignPatternsAdapterAndFacadeDesignPattern.Assignment.FacadeData.ActualQuestion.service;

import lowLevelDesignModuleTwo.QuestionAnswer.BackendLLDDesignPatternsAdapterAndFacadeDesignPattern.Assignment.FacadeData.ActualQuestion.model.AnalysisAlgorithmConfig;
import lowLevelDesignModuleTwo.QuestionAnswer.BackendLLDDesignPatternsAdapterAndFacadeDesignPattern.Assignment.FacadeData.ActualQuestion.model.AnalysisResult;
import lowLevelDesignModuleTwo.QuestionAnswer.BackendLLDDesignPatternsAdapterAndFacadeDesignPattern.Assignment.FacadeData.ActualQuestion.model.PreProcessedData;

public class AnalysisAlgorithmService {
    public AnalysisResult applyAnalysisAlgorithm(PreProcessedData preProcessedData, AnalysisAlgorithmConfig analysisAlgorithmConfig) {
        return new AnalysisResult();
    }
}
